# Generated by Django 2.1.7 on 2019-03-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giornata', models.IntegerField()),
                ('ar', models.CharField(db_column='AR', max_length=1)),
                ('data', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Calendario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campionati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Campionati',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Risultati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retilocali', models.IntegerField(db_column='retiLocali')),
                ('retiospiti', models.IntegerField(db_column='retiOspiti')),
            ],
            options={
                'db_table': 'Risultati',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Squadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Squadre',
                'managed': False,
            },
        ),
    ]
